import { eq } from "drizzle-orm";
import { describe, expect, it } from "vitest";
import { db } from "@/db/client.js";
import { projectReports } from "@/db/schema/project-reports.js";
import { projects } from "@/db/schema/projects.js";
import { reportAttachments } from "@/db/schema/report-attachments.js";
import { sdgs } from "@/db/schema/sdgs.js";
import { proposalSdgs } from "@/db/schema/proposal-sdgs.js";
import { getAnalytics } from "@/modules/analytics/analytics.service.js";
import { AnalyticsQuery } from "@/modules/analytics/analytics.schema.js";
import { finalizeTerminalPackage } from "@/modules/reports/terminal-package.js";
import { closeProject } from "@/modules/projects/projects.service.js";
import { ROLE_NAMES, REPORT_TYPE } from "@/lib/types.js";
import { seedAuthUser, seedOrganization, seedProposal, seedProposalMember, seedProject, seedMilestone, seedReport } from "./fixtures.js";

describe("extension analytics integration", () => {
	it("finalizes only after evaluation evidence, counts approved results once, and enforces scope", async () => {
		const org = await seedOrganization("analytics");
		const leader = await seedAuthUser(org, { slug: "leader", roleName: ROLE_NAMES.FACULTY });
		const outsider = await seedAuthUser(org, { slug: "outsider", roleName: ROLE_NAMES.FACULTY });
		const director = await seedAuthUser(org, { slug: "director", roleName: ROLE_NAMES.DIRECTOR, department: null });
		const chairB = await seedAuthUser(org, { slug: "chair", roleName: ROLE_NAMES.RET_CHAIR, department: org.departmentB });
		const proposal = await seedProposal(org, { title: "Trainee project" });
		await seedProposalMember(proposal.proposalId, leader.userId, "Project Leader");
		const project = await seedProject(proposal.proposalId, { status: "Ongoing" });
		const milestone = await seedMilestone(project.projectId, "Terminal Report", new Date("2099-12-01"));
		const report = await seedReport(project.projectId, milestone.milestoneId, leader.userId, { reportType: REPORT_TYPE.ACCOMPLISHMENT_AND_TERMINAL, storagePath: "reports/terminal.pdf" });
		await db.update(projectReports).set({ traineeCount: 0, submittedAt: new Date() }).where(eq(projectReports.reportId, report.reportId));
		expect(await db.transaction((tx) => finalizeTerminalPackage(tx, report.reportId, leader, "127.0.0.1"))).toBe(false);
		await db.insert(reportAttachments).values({ reportId: report.reportId, attachmentType: "Evaluation Forms", storagePath: "reports/eval.pdf" });
		expect(await db.transaction((tx) => finalizeTerminalPackage(tx, report.reportId, leader, "127.0.0.1"))).toBe(true);
		expect(await db.transaction((tx) => finalizeTerminalPackage(tx, report.reportId, leader, "127.0.0.1"))).toBe(false);
		const filters = AnalyticsQuery.parse({ year: new Date().getFullYear() });
		expect((await getAnalytics(director, filters, "reach")).total).toBe(0);
		await closeProject(project.projectId, director, "127.0.0.1");
		let results = await getAnalytics(director, filters, "reach");
		expect(results.total).toBe(1); expect(results.items[0]?.traineeCount).toBe(0); expect(results.metrics[1]?.value).toBe(1);
		const goals = await db.insert(sdgs).values([{ sdgNumber: 3, sdgTitle: "Health" }, { sdgNumber: 4, sdgTitle: "Education" }]).returning();
		await db.insert(proposalSdgs).values(goals.map((goal) => ({ proposalId: proposal.proposalId, sdgId: goal.sdgId })));
		results = await getAnalytics(director, filters, "reach"); expect(results.metrics[0]?.value).toBe(0);
		const coverage = await getAnalytics(director, { ...filters, groupBy: "sdg" }, "coverage");
		expect(coverage.total).toBe(1); expect(coverage.groups).toHaveLength(2);
		expect((await getAnalytics(outsider, filters, "reach")).total).toBe(0);
		expect((await getAnalytics(chairB, { ...filters, departmentId: org.departmentA.departmentId }, "reach")).total).toBe(0);
		const faculty = await getAnalytics(director, filters, "participation");
		expect(faculty.items.find((item) => item.userId === leader.userId)?.projects).toBe(0);
		const [saved] = await db.select().from(projects).where(eq(projects.projectId, project.projectId));
		expect(saved.projectStatus).toBe("Closed");
	});
});
