/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as RegisterAccountRouteImport } from './routes/register.account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedMoasIndexRouteImport } from './routes/_authenticated/moas/index'
import { Route as AuthenticatedFacultyIndexRouteImport } from './routes/_authenticated/faculty/index'
import { Route as AuthenticatedProposalsProposalIdRouteImport } from './routes/_authenticated/proposals/$proposalId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedAdminActivityLogIndexRouteImport } from './routes/_authenticated/admin/activity-log/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const RegisterAccountRoute = RegisterAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => RegisterRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMoasIndexRoute = AuthenticatedMoasIndexRouteImport.update({
  id: '/moas/',
  path: '/moas/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacultyIndexRoute =
  AuthenticatedFacultyIndexRouteImport.update({
    id: '/faculty/',
    path: '/faculty/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProposalsProposalIdRoute =
  AuthenticatedProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityLogIndexRoute =
  AuthenticatedAdminActivityLogIndexRouteImport.update({
    id: '/activity-log/',
    path: '/activity-log/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/register/account': typeof RegisterAccountRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/faculty/': typeof AuthenticatedFacultyIndexRoute
  '/moas/': typeof AuthenticatedMoasIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/admin/activity-log/': typeof AuthenticatedAdminActivityLogIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/register/account': typeof RegisterAccountRoute
  '/': typeof AuthenticatedIndexRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/faculty': typeof AuthenticatedFacultyIndexRoute
  '/moas': typeof AuthenticatedMoasIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/register/account': typeof RegisterAccountRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/_authenticated/faculty/': typeof AuthenticatedFacultyIndexRoute
  '/_authenticated/moas/': typeof AuthenticatedMoasIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/admin/activity-log/': typeof AuthenticatedAdminActivityLogIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/register/account'
    | '/proposals/$proposalId'
    | '/faculty/'
    | '/moas/'
    | '/projects/'
    | '/reports/'
    | '/admin/activity-log/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/register/account'
    | '/'
    | '/proposals/$proposalId'
    | '/faculty'
    | '/moas'
    | '/projects'
    | '/reports'
    | '/admin/activity-log'
    | '/admin/settings'
    | '/admin/users'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/register/account'
    | '/_authenticated/'
    | '/_authenticated/proposals/$proposalId'
    | '/_authenticated/faculty/'
    | '/_authenticated/moas/'
    | '/_authenticated/projects/'
    | '/_authenticated/reports/'
    | '/_authenticated/admin/activity-log/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/register/account': {
      id: '/register/account'
      path: '/account'
      fullPath: '/register/account'
      preLoaderRoute: typeof RegisterAccountRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moas/': {
      id: '/_authenticated/moas/'
      path: '/moas'
      fullPath: '/moas/'
      preLoaderRoute: typeof AuthenticatedMoasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faculty/': {
      id: '/_authenticated/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof AuthenticatedFacultyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proposals/$proposalId': {
      id: '/_authenticated/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof AuthenticatedProposalsProposalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity-log/': {
      id: '/_authenticated/admin/activity-log/'
      path: '/activity-log'
      fullPath: '/admin/activity-log/'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityLogIndexRoute: typeof AuthenticatedAdminActivityLogIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityLogIndexRoute:
    AuthenticatedAdminActivityLogIndexRoute,
  AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProposalsProposalIdRoute: typeof AuthenticatedProposalsProposalIdRoute
  AuthenticatedFacultyIndexRoute: typeof AuthenticatedFacultyIndexRoute
  AuthenticatedMoasIndexRoute: typeof AuthenticatedMoasIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProposalsProposalIdRoute: AuthenticatedProposalsProposalIdRoute,
  AuthenticatedFacultyIndexRoute: AuthenticatedFacultyIndexRoute,
  AuthenticatedMoasIndexRoute: AuthenticatedMoasIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface RegisterRouteChildren {
  RegisterAccountRoute: typeof RegisterAccountRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterAccountRoute: RegisterAccountRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
